export const FREE_DAILY_LESSON_AI_LIMIT = 10;
export const FREE_MONTHLY_LESSON_AI_REFINE_LIMIT = 20;
export const FREE_GENERATED_ASSET_LIMIT_PER_LESSON = 2;
export const PLUS_GENERATED_ASSET_LIMIT_PER_LESSON = 2;
